import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import builtin from "builtin-modules";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtin,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

// After a successful build, copy the plugin artifacts into the Obsidian plugins folder.
// The vault root is `../vault`, so install into `../vault/.obsidian/plugins/fuwari-tools`.
const pluginDir = path.resolve(__dirname, "..", "vault", ".obsidian", "plugins", "fuwari-tools");

function copyArtifacts() {
	fs.mkdirSync(pluginDir, { recursive: true });
	const files = ["main.js", "manifest.json", "styles.css"];
	for (const f of files) {
		const src = path.resolve(__dirname, f);
		if (fs.existsSync(src)) {
			fs.copyFileSync(src, path.join(pluginDir, f));
			console.log(`copied ${f} -> ${path.join(pluginDir, f)}`);
		}
	}
}

if (prod) {
	await context.rebuild();
	await context.dispose();
	copyArtifacts();
} else {
	await context.watch();
}
