/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => FuwariToolsPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");
var import_child_process = require("child_process");
var import_os = require("os");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  postsFolder: "vault/posts",
  imagesFolder: "vault/images",
  autoUpdateUpdated: true,
  updateDrafts: false,
  warnOnSave: true,
  autoFillPublished: false,
  aiEnabled: false,
  aiBaseUrl: "https://api.deepseek.com/v1",
  aiModel: "deepseek-chat",
  aiApiKey: "",
  aiMaxChars: 2e3,
  aiGenerateTags: false,
  publishEnabled: true,
  publishScriptPath: "~/Documents/Projects/Blog/publish.sh"
};
var FuwariSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("\u6587\u7AE0\u76EE\u5F55").setDesc("vault \u5185\u76F8\u5BF9\u8DEF\u5F84").addText((t) => t.setPlaceholder("vault/posts").setValue(this.plugin.settings.postsFolder).onChange(async (v) => {
      this.plugin.settings.postsFolder = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u56FE\u7247\u76EE\u5F55").setDesc("\u5C01\u9762/\u63D2\u56FE\u5B58\u653E\u76EE\u5F55").addText((t) => t.setPlaceholder("vault/images").setValue(this.plugin.settings.imagesFolder).onChange(async (v) => {
      this.plugin.settings.imagesFolder = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58\u65F6\u81EA\u52A8\u66F4\u65B0 updated").addToggle((t) => t.setValue(this.plugin.settings.autoUpdateUpdated).onChange(async (v) => {
      this.plugin.settings.autoUpdateUpdated = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u4E5F\u66F4\u65B0\u8349\u7A3F\uFF08draft:true\uFF09").addToggle((t) => t.setValue(this.plugin.settings.updateDrafts).onChange(async (v) => {
      this.plugin.settings.updateDrafts = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u4FDD\u5B58\u65F6\u63D0\u9192\u7F3A\u5FC5\u586B\u5B57\u6BB5").addToggle((t) => t.setValue(this.plugin.settings.warnOnSave).onChange(async (v) => {
      this.plugin.settings.warnOnSave = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u8865 published").setDesc("\u5DF2\u53D1\u5E03\u6587\u7AE0\u7F3A\u65E5\u671F\u65F6\u4FDD\u5B58\u8865\u5F53\u5929").addToggle((t) => t.setValue(this.plugin.settings.autoFillPublished).onChange(async (v) => {
      this.plugin.settings.autoFillPublished = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "AI \u6458\u8981" });
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528 AI \u751F\u6210\u6458\u8981").addToggle((t) => t.setValue(this.plugin.settings.aiEnabled).onChange(async (v) => {
      this.plugin.settings.aiEnabled = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Base URL").setDesc("OpenAI \u517C\u5BB9\u7AEF\u70B9\uFF0C\u5982 DeepSeek").addText((t) => t.setPlaceholder("https://api.deepseek.com/v1").setValue(this.plugin.settings.aiBaseUrl).onChange(async (v) => {
      this.plugin.settings.aiBaseUrl = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").addText((t) => t.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.aiModel).onChange(async (v) => {
      this.plugin.settings.aiModel = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u4EC5\u4FDD\u5B58\u5728\u672C\u5730 data.json").addText((t) => {
      t.setPlaceholder("sk-...").setValue(this.plugin.settings.aiApiKey).onChange(async (v) => {
        this.plugin.settings.aiApiKey = v;
        await this.plugin.saveSettings();
      });
      t.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("\u53D1\u9001\u6B63\u6587\u5B57\u7B26\u6570\u4E0A\u9650").addText((t) => t.setValue(String(this.plugin.settings.aiMaxChars)).onChange(async (v) => {
      const n = parseInt(v, 10);
      this.plugin.settings.aiMaxChars = isNaN(n) || n < 100 ? 2e3 : n;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("AI \u987A\u5E26\u751F\u6210 tags/category").addToggle((t) => t.setValue(this.plugin.settings.aiGenerateTags).onChange(async (v) => {
      this.plugin.settings.aiGenerateTags = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u53D1\u5E03" });
    new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u4E00\u952E\u53D1\u5E03").addToggle((t) => t.setValue(this.plugin.settings.publishEnabled).onChange(async (v) => {
      this.plugin.settings.publishEnabled = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u53D1\u5E03\u811A\u672C\u8DEF\u5F84").addText((t) => t.setPlaceholder("~/Documents/Projects/Blog/publish.sh").setValue(this.plugin.settings.publishScriptPath).onChange(async (v) => {
      this.plugin.settings.publishScriptPath = v;
      await this.plugin.saveSettings();
    }));
  }
};

// src/fm.ts
function isUnder(p, folder) {
  const f = folder.replace(/\/+$/, "");
  return p === f || p.startsWith(f + "/");
}
function isPostFile(file, postsFolder) {
  return file.extension === "md" && isUnder(file.path, postsFolder);
}
function getFrontmatter(app, file) {
  var _a;
  const cache = app.metadataCache.getFileCache(file);
  return (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : null;
}
function slugify(title) {
  let s = title.trim();
  s = s.replace(/\\/g, "/");
  s = s.replace(/[\/:*?"<>|]/g, " ").replace(/\s+/g, "-").replace(/^-+|-+$/g, "").replace(/^\.+|[.\s]+$/g, "");
  if (s.length > 80)
    s = s.slice(0, 80).replace(/-+$/g, "");
  if (!s) {
    const t = /* @__PURE__ */ new Date();
    const pad = (n) => String(n).padStart(2, "0");
    s = `post-${t.getFullYear()}${pad(t.getMonth() + 1)}${pad(t.getDate())}-${pad(t.getHours())}${pad(t.getMinutes())}${pad(t.getSeconds())}`;
  }
  return s;
}
function sanitizeFileName(name) {
  const base = name.replace(/[^\w.\-]/g, "").replace(/^\.+/, "");
  return base || `image-${Date.now()}.png`;
}

// src/meta-modal.ts
var import_obsidian4 = require("obsidian");

// src/cover.ts
var import_obsidian2 = require("obsidian");
var IMAGE_EXTS = /* @__PURE__ */ new Set(["png", "jpg", "jpeg", "gif", "webp", "svg", "avif"]);
function listImages(app, imagesFolder) {
  return app.vault.getFiles().filter((f) => {
    if (!IMAGE_EXTS.has(f.extension) || !isUnder(f.path, imagesFolder))
      return false;
    return true;
  });
}
async function ensureFolder(app, folder) {
  if (!folder)
    return;
  if (!app.vault.getAbstractFileByPath(folder)) {
    await app.vault.createFolder(folder);
  }
}
function resourcePath(app, file) {
  try {
    return app.vault.getResourcePath(file);
  } catch (e) {
    return "";
  }
}
async function importImage(app, imagesFolder, rawName, data) {
  await ensureFolder(app, imagesFolder);
  const safe = sanitizeFileName(rawName);
  let name = safe;
  let i = 1;
  while (app.vault.getAbstractFileByPath(`${imagesFolder}/${name}`)) {
    const ext = name.includes(".") ? name.slice(name.lastIndexOf(".")) : "";
    const stem = name.slice(0, name.lastIndexOf("."));
    name = `${stem}-${i++}${ext}`;
  }
  await app.vault.createBinary(`${imagesFolder}/${name}`, data);
  return `/images/${name}`;
}
var CoverSuggestModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, imagesFolder, onPick) {
    super(app);
    this.imagesFolder = imagesFolder;
    this.onPick = onPick;
    this.setPlaceholder("\u9009\u62E9\u5C01\u9762\u56FE\u2026");
  }
  getItems() {
    return listImages(this.app, this.imagesFolder);
  }
  getItemText(item) {
    return item.path;
  }
  renderSuggestion(match, el) {
    const item = match.item;
    el.createEl("div", { cls: "fuwari-cover-item" }, (d) => {
      const img = d.createEl("img");
      img.src = resourcePath(this.app, item);
      img.addClass("fuwari-cover-thumb");
      const label = d.createEl("span", { text: item.basename });
      label.addClass("fuwari-cover-label");
    });
  }
  onChooseItem(item) {
    this.onPick(item);
  }
};

// src/ai.ts
var import_obsidian3 = require("obsidian");
function cleanBody(content, maxChars) {
  const trimmed = content.replace(/^\s*---\r?\n[\s\S]*?\r?\n---\r?\n?/, "").trim();
  return trimmed.slice(0, maxChars);
}
function joinList(items) {
  return items.map((s) => String(s).trim()).filter(Boolean);
}
async function generateSummary(content, settings) {
  var _a, _b, _c, _d;
  const body = cleanBody(content, settings.aiMaxChars);
  const wantTags = settings.aiGenerateTags;
  let systemPrompt = "\u4F60\u662F\u4E00\u4E2A\u535A\u5BA2\u52A9\u624B\u3002\u8BF7\u4E3A\u6587\u7AE0\u5199\u4E00\u53E5\u7B80\u77ED\u7684\u6982\u8FF0\uFF08\u4E2D\u6587\uFF0C\u4E0D\u8D85\u8FC7 50 \u5B57\uFF0C\u4F46 20 \u5B57\u4EE5\u5185\u6700\u4F73\u3001\u8D8A\u77ED\u8D8A\u597D\uFF09\uFF0C\u6734\u7D20\u5BA2\u89C2\u3001\u50CF\u4E00\u53E5\u8BDD\u526F\u6807\u9898\uFF0C\u4E0D\u8981\u8425\u9500\u8BCD\u3001\u4E0D\u8981\u5F15\u53F7\u3001\u4E0D\u8981\u300C\u6982\u8FF0\uFF1A\u300D\u524D\u7F00\uFF0C\u76F4\u63A5\u8F93\u51FA\u6982\u8FF0\u672C\u8EAB\u3002\u793A\u4F8B\uFF1A\u8FD9\u662F\u4E00\u7BC7 Markdown \u535A\u5BA2\u793A\u4F8B\u3002";
  if (wantTags) {
    systemPrompt += ' \u53E6\u5916\u518D\u7528 JSON \u8F93\u51FA\u63A8\u8350\u6807\u7B7E\u4E0E\u5206\u7C7B\uFF1A\u5F62\u5982 {"tags": ["\u6807\u7B7E1","\u6807\u7B7E2"], "category": "\u5206\u7C7B"}\uFF0C\u653E\u5728\u6982\u8FF0\u4E4B\u540E\uFF0C\u7528 --- \u5206\u9694\u3002';
  }
  const userPrompt = wantTags ? `\u6587\u7AE0\u5185\u5BB9\uFF1A

${body}

\u8BF7\u8F93\u51FA\uFF1A\u7B2C\u4E00\u884C\u4E3A\u4E2D\u6587\u6982\u8FF0\uFF08\u226450\u5B57\uFF0C\u5C3D\u91CF\u226420\u5B57\uFF09\uFF1B\u7136\u540E\u4E00\u884C ---\uFF1B\u7136\u540E\u4E00\u884C JSON \u5F62\u5982 {"tags":["a","b"],"category":"c"}\u3002` : `\u6587\u7AE0\u5185\u5BB9\uFF1A

${body}`;
  const payload = {
    model: settings.aiModel,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt }
    ],
    temperature: 0.3,
    max_tokens: 500
  };
  const base = settings.aiBaseUrl.replace(/\/+$/, "");
  const resp = await (0, import_obsidian3.requestUrl)({
    url: `${base}/chat/completions`,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${settings.aiApiKey}`
    },
    body: JSON.stringify(payload)
  });
  if (resp.status < 200 || resp.status >= 300) {
    throw new Error(`AI API ${resp.status}: ${(resp.text || "").slice(0, 200)}`);
  }
  const data = resp.json;
  const text = ((_d = (_c = (_b = (_a = data == null ? void 0 : data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) == null ? void 0 : _d.trim()) || "";
  if (!wantTags) {
    return { summary: text, tags: [], category: "" };
  }
  const lines = text.split(/\r?\n/);
  const sep = lines.findIndex((l) => /^---+$/.test(l.trim()));
  const summary = sep >= 0 ? lines.slice(0, sep).join("\n").trim() : text;
  let tags = [];
  let category = "";
  if (sep >= 0) {
    const jsonPart = lines.slice(sep + 1).join("\n").trim();
    const m = jsonPart.match(/\{[\s\S]*\}/);
    if (m) {
      try {
        const obj = JSON.parse(m[0]);
        tags = joinList(obj.tags || []);
        category = String(obj.category || "").trim();
      } catch (e) {
      }
    }
  }
  return { summary, tags, category };
}

// src/meta-modal.ts
function dateVal(v) {
  if (v == null || v === "")
    return "";
  if (typeof v === "string")
    return v;
  if (v instanceof Date)
    return (0, import_obsidian4.moment)(v).format("YYYY-MM-DD");
  if (typeof v === "object" && v !== null) {
    const d = v;
    if (d.year && d.day && d.month) {
      return `${d.year}-${String(d.month).padStart(2, "0")}-${String(d.day).padStart(2, "0")}`;
    }
  }
  return String(v);
}
function splitTags(input) {
  return input.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);
}
var MetaModal = class extends import_obsidian4.Modal {
  constructor(app, file, plugin) {
    super(app);
    this.file = file;
    this.plugin = plugin;
  }
  async onOpen() {
    const fm = getFrontmatter(this.app, this.file) || {};
    this.form = {
      title: fm.title || this.file.basename,
      published: dateVal(fm.published),
      updated: dateVal(fm.updated),
      description: fm.description || "",
      category: fm.category || "",
      tags: Array.isArray(fm.tags) ? fm.tags.join(", ") : String(fm.tags || ""),
      draft: fm.draft === true,
      image: fm.image || ""
    };
    const { contentEl } = this;
    contentEl.createEl("h2", { text: `\u6587\u7AE0\u5143\u6570\u636E \u2014 ${this.file.basename}` });
    const add = (name, desc) => new import_obsidian4.Setting(contentEl).setName(name).setDesc(desc);
    add("\u6807\u9898", "\u6587\u7AE0\u6807\u9898\uFF08\u6587\u4EF6\u540D\u4FDD\u7559\u4E3A slug\uFF09").addText((t) => t.setValue(this.form.title).onChange((v) => this.form.title = v));
    add("\u53D1\u5E03\u65E5\u671F published", "\u5FC5\u586B\uFF0CYYYY-MM-DD").addText((t) => t.setPlaceholder("2026-08-30").setValue(this.form.published).onChange((v) => this.form.published = v));
    add("\u66F4\u65B0\u65E5\u671F updated", "\u4FDD\u5B58\u65F6\u81EA\u52A8\u7EF4\u62A4").addText((t) => t.setPlaceholder("2026-08-30").setValue(this.form.updated).onChange((v) => this.form.updated = v));
    add("\u6458\u8981 description", "\u9996\u9875\u5217\u8868\u663E\u793A").addTextArea((t) => {
      this.descEl = t.inputEl;
      t.setPlaceholder("\u4E00\u53E5\u8BDD\u6458\u8981").setValue(this.form.description).onChange((v) => this.form.description = v);
    });
    add("\u5206\u7C7B category", "\u5355\u4E2A\u5B57\u7B26\u4E32").addText((t) => t.setValue(this.form.category).onChange((v) => this.form.category = v));
    add("\u6807\u7B7E tags", "\u9017\u53F7\u5206\u9694").addText((t) => {
      this.tagsEl = t.inputEl;
      t.setValue(this.form.tags).onChange((v) => this.form.tags = v);
    });
    add("\u8349\u7A3F draft", "true \u5219\u4E0D\u4F1A\u53D1\u5E03\u5230\u7EBF\u4E0A").addToggle((t) => t.setValue(this.form.draft).onChange((v) => this.form.draft = v));
    const coverSetting = add("\u5C01\u9762 image", "\u4ECE images \u76EE\u5F55\u9009\u53D6\uFF0C\u6216\u4E0A\u4F20").addButton((b) => b.setButtonText("\u9009\u53D6").onClick(() => this.pickCover()));
    coverSetting.addButton((b) => b.setButtonText("\u4E0A\u4F20").onClick(() => this.uploadCover()));
    coverSetting.addButton((b) => b.setButtonText("\u79FB\u9664").onClick(() => {
      this.form.image = "";
      this.updateCoverPreview();
    }));
    const wrap = contentEl.createDiv({ cls: "fuwari-cover-preview" });
    this.coverImg = wrap.createEl("img", { cls: "fuwari-cover-preview-img" });
    this.updateCoverPreview();
    const statusWrap = contentEl.createDiv({ cls: "fuwari-status" });
    statusWrap.createEl("span", { text: "" });
    this.statusEl = statusWrap;
    this.statusEl.style.display = "none";
    new import_obsidian4.Setting(contentEl).setName("AI \u751F\u6210\u6458\u8981").setDesc("\u8C03\u7528\u914D\u7F6E\u7684 OpenAI \u517C\u5BB9\u63A5\u53E3").addButton((b) => b.setButtonText("\u751F\u6210\u6458\u8981").setCta().onClick(async () => {
      await this.runAi();
    }));
    const footer = contentEl.createDiv({ cls: "fuwari-modal-footer" });
    const saveBtn = footer.createEl("button", { text: "\u4FDD\u5B58", cls: "mod-cta" });
    saveBtn.addEventListener("click", () => this.save());
    const cancelBtn = footer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.addEventListener("click", () => this.close());
    this.contentEl.addEventListener("paste", (evt) => {
      var _a;
      const item = Array.from(((_a = evt.clipboardData) == null ? void 0 : _a.items) || []).find((i) => i.type.startsWith("image/"));
      if (item) {
        const file = item.getAsFile();
        if (file) {
          evt.preventDefault();
          this.setStatus("\u6B63\u5728\u4FDD\u5B58\u7C98\u8D34\u7684\u5C01\u9762\u2026");
          void (async () => {
            try {
              const buf = await file.arrayBuffer();
              const p = await importImage(this.app, this.plugin.settings.imagesFolder, "pasted.png", buf);
              this.form.image = p;
              this.updateCoverPreview();
              this.setStatus("\u2705 \u5C01\u9762\u5DF2\u4EE5\u7C98\u8D34\u56FE\u7247\u66F4\u65B0", "ok");
              new import_obsidian4.Notice("\u5C01\u9762\u5DF2\u4EE5\u7C98\u8D34\u56FE\u7247\u66F4\u65B0");
            } catch (e) {
              const msg = e.message;
              this.setStatus("\u7C98\u8D34\u5931\u8D25: " + msg, "err");
              new import_obsidian4.Notice("\u7C98\u8D34\u5931\u8D25: " + msg);
            }
          })();
        }
      }
    });
  }
  setStatus(text, kind) {
    this.statusEl.style.display = "block";
    this.statusEl.setText(text);
    this.statusEl.removeClass("ok");
    this.statusEl.removeClass("err");
    if (kind === "ok")
      this.statusEl.addClass("ok");
    else if (kind === "err")
      this.statusEl.addClass("err");
  }
  updateCoverPreview() {
    const path = this.form.image;
    let src = "";
    if (path) {
      const imagesFolder = this.plugin.settings.imagesFolder.replace(/\/+$/, "");
      const base = path.replace(/^\//, "");
      const name = base.startsWith("images/") ? base.slice(7) : base;
      const file = this.app.vault.getAbstractFileByPath(`${imagesFolder}/${name}`);
      if (file instanceof import_obsidian4.TFile)
        src = resourcePath(this.app, file);
    }
    this.coverImg.style.display = src ? "block" : "none";
    this.coverImg.src = src;
  }
  pickCover() {
    new CoverSuggestModal(this.app, this.plugin.settings.imagesFolder, (file) => {
      this.form.image = `/images/${file.name}`;
      this.updateCoverPreview();
    }).open();
  }
  uploadCover() {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/*";
    input.onchange = async () => {
      var _a;
      const f = (_a = input.files) == null ? void 0 : _a[0];
      if (!f)
        return;
      this.setStatus("\u6B63\u5728\u4E0A\u4F20\u5C01\u9762\u2026");
      try {
        const buf = await f.arrayBuffer();
        const p = await importImage(this.app, this.plugin.settings.imagesFolder, f.name, buf);
        this.form.image = p;
        this.updateCoverPreview();
        this.setStatus("\u2705 \u5C01\u9762\u5DF2\u4E0A\u4F20", "ok");
        new import_obsidian4.Notice("\u5C01\u9762\u5DF2\u4E0A\u4F20");
      } catch (e) {
        const msg = e.message;
        this.setStatus("\u4E0A\u4F20\u5931\u8D25: " + msg, "err");
        new import_obsidian4.Notice("\u4E0A\u4F20\u5931\u8D25: " + msg);
      }
    };
    input.click();
  }
  async runAi() {
    if (!this.plugin.settings.aiEnabled || !this.plugin.settings.aiApiKey) {
      new import_obsidian4.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u542F\u7528 AI \u5E76\u586B\u5199 API Key");
      return;
    }
    let content;
    try {
      content = await this.app.vault.read(this.file);
    } catch (e) {
      new import_obsidian4.Notice("\u8BFB\u53D6\u6587\u7AE0\u5931\u8D25: " + e.message);
      return;
    }
    this.setStatus("\u6B63\u5728\u751F\u6210\u6458\u8981\u2026");
    try {
      const result = await generateSummary(content, this.plugin.settings);
      this.form.description = result.summary;
      this.descEl.value = result.summary;
      if (this.plugin.settings.aiGenerateTags) {
        if (result.tags.length) {
          this.form.tags = result.tags.join(", ");
          this.tagsEl.value = this.form.tags;
        }
        if (result.category) {
          this.form.category = result.category;
        }
      }
      this.setStatus("\u2705 \u6458\u8981\u5DF2\u751F\u6210\uFF0C\u53EF\u7F16\u8F91\u540E\u4FDD\u5B58", "ok");
      new import_obsidian4.Notice("\u6458\u8981\u5DF2\u751F\u6210\uFF0C\u53EF\u7F16\u8F91\u540E\u4FDD\u5B58");
    } catch (e) {
      const msg = e.message;
      this.setStatus("AI \u751F\u6210\u5931\u8D25: " + msg, "err");
      new import_obsidian4.Notice("AI \u751F\u6210\u5931\u8D25: " + msg);
    }
  }
  async save() {
    const f = this.form;
    await this.app.fileManager.processFrontMatter(this.file, (fm) => {
      fm.title = f.title;
      if (f.published)
        fm.published = f.published;
      if (f.updated)
        fm.updated = f.updated;
      fm.description = f.description;
      fm.category = f.category;
      fm.tags = splitTags(f.tags);
      fm.draft = f.draft;
      if (f.image)
        fm.image = f.image;
      else
        delete fm.image;
      if (this.plugin.settings.autoFillPublished && !fm.published && fm.draft === false) {
        fm.published = (0, import_obsidian4.moment)().format("YYYY-MM-DD");
      }
    });
    this.close();
    new import_obsidian4.Notice("\u5DF2\u4FDD\u5B58");
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/render.ts
var import_obsidian5 = require("obsidian");
function registerBlogRender(plugin) {
  plugin.registerMarkdownPostProcessor(async (el, ctx) => {
    try {
      processSpoilers(el);
      processGithubCards(el);
      await processAdmonitions(plugin, el, ctx.sourcePath);
    } catch (e) {
      console.error("[fuwari-tools] post-processor error:", e);
    }
  });
}
function processSpoilers(el) {
  for (const p of Array.from(el.querySelectorAll("p"))) {
    if (!p.innerHTML.includes(":spoiler["))
      continue;
    p.innerHTML = p.innerHTML.replace(/:spoiler\[([^\]]*)\]/g, '<span class="fuwari-spoiler">$1</span>');
  }
}
function processGithubCards(el) {
  const paragraphs = Array.from(el.querySelectorAll("p"));
  for (const p of paragraphs) {
    if (p.closest("pre, code") || p.querySelector("code"))
      continue;
    const text = p.textContent || "";
    const re = /::\s*github\s*\{\s*repo\s*=\s*"([^"]+)"\s*\}/g;
    const found = Array.from(text.matchAll(re));
    if (!found.length)
      continue;
    if (text.replace(re, "").trim() !== "")
      continue;
    const fragment = p.ownerDocument.createDocumentFragment();
    for (const m of found) {
      const repo = m[1];
      const card = buildGithubCard(repo);
      fragment.appendChild(card);
      void hydrateGithubCard(card, repo);
    }
    p.replaceWith(fragment);
  }
}
var OCTO_SVG = '<svg viewBox="0 0 16 16" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8Z"/></svg>';
function buildGithubCard(repo) {
  const card = document.createElement("div");
  card.addClass("fuwari-github-card");
  const head = card.createDiv({ cls: "fuwari-github-head" });
  const left = head.createDiv({ cls: "fuwari-github-head-left" });
  const avatar = left.createEl("img", { cls: "fuwari-github-avatar" });
  avatar.setAttr("alt", "");
  avatar.style.visibility = "hidden";
  left.createSpan({ cls: "fuwari-github-name", text: repo });
  const mark = head.createSpan({ cls: "fuwari-github-mark" });
  mark.innerHTML = OCTO_SVG;
  mark.setAttr("aria-hidden", "true");
  card.createDiv({ cls: "fuwari-github-desc", text: "\u52A0\u8F7D\u4E2D\u2026" });
  card.createDiv({ cls: "fuwari-github-meta" });
  card.createEl("a", {
    cls: "fuwari-github-link",
    href: `https://github.com/${repo}`,
    text: `github.com/${repo}`
  }).setAttr("target", "_blank");
  return card;
}
async function hydrateGithubCard(card, repo) {
  var _a, _b, _c, _d, _e;
  const desc = card.querySelector(".fuwari-github-desc");
  const meta = card.querySelector(".fuwari-github-meta");
  const avatar = card.querySelector("img.fuwari-github-avatar");
  const name = card.querySelector(".fuwari-github-name");
  try {
    const resp = await fetch(`https://api.github.com/repos/${repo}`);
    if (!resp.ok)
      throw new Error(`HTTP ${resp.status}`);
    const data = await resp.json();
    if (desc)
      desc.setText(data.description || "\uFF08\u65E0\u63CF\u8FF0\uFF09");
    if (name) {
      const idx = repo.indexOf("/");
      if (idx > 0) {
        const owner = repo.slice(0, idx);
        const short = repo.slice(idx + 1);
        name.innerHTML = `<span class="fuwari-github-owner">${escapeHtml(owner)}</span> <span class="fuwari-github-repo">/ ${escapeHtml(short)}</span>`;
      }
    }
    if (avatar && ((_a = data.owner) == null ? void 0 : _a.avatar_url)) {
      avatar.setAttribute("src", data.owner.avatar_url);
      avatar.style.visibility = "visible";
    }
    if (meta) {
      const stars = (_b = data.stargazers_count) != null ? _b : 0;
      const forks = (_c = data.forks_count) != null ? _c : 0;
      const lic = ((_d = data.license) == null ? void 0 : _d.spdx_id) || ((_e = data.license) == null ? void 0 : _e.name) || "";
      meta.innerHTML = `<span class="fuwari-github-stat">${STAR_SVG} ${stars}</span><span class="fuwari-github-stat">${FORK_SVG} ${forks}</span>` + (lic ? `<span class="fuwari-github-stat">${LICENSE_SVG} ${escapeHtml(lic)}</span>` : "");
    }
  } catch (e) {
    if (desc)
      desc.setText(repo + "\uFF08GitHub API \u6682\u65F6\u65E0\u6CD5\u52A0\u8F7D\uFF09");
  }
}
function escapeHtml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
var STAR_SVG = '<svg viewBox="0 0 16 16" width="14" height="14" fill="currentColor" aria-hidden="true"><path d="M8 .25a.75.75 0 0 1 .673.418l1.882 3.815 4.21.612a.75.75 0 0 1 .416 1.279l-3.046 2.97.719 4.192a.751.751 0 0 1-1.088.791L8 12.347l-3.766 1.98a.75.75 0 0 1-1.088-.79l.72-4.194L.818 6.374a.75.75 0 0 1 .416-1.28l4.21-.611L7.327.668A.75.75 0 0 1 8 .25Z"/></svg>';
var FORK_SVG = '<svg viewBox="0 0 16 16" width="14" height="14" fill="currentColor" aria-hidden="true"><path d="M5 5.372v.878c0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75v-.878a2.25 2.25 0 1 1 1.5 0v.878a2.25 2.25 0 0 1-2.25 2.25h-1.5v2.128a2.251 2.251 0 1 1-1.5 0V8.5h-1.5A2.25 2.25 0 0 1 3.5 6.25v-.878a2.25 2.25 0 1 1 1.5 0ZM5 3.25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Zm6.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm-3 8.75a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z"/></svg>';
var LICENSE_SVG = '<svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/><path d="M7 21h10"/><path d="M12 3v18"/><path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/></svg>';
function capitalise(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
function blockToMarkdown(b) {
  const text = (b.textContent || "").replace(/\s+/g, " ").trim();
  if (!text)
    return [];
  switch (b.tagName) {
    case "H1":
      return ["# " + text];
    case "H2":
      return ["## " + text];
    case "H3":
      return ["### " + text];
    case "UL":
      return Array.from(b.children).map((li) => "- " + (li.textContent || "").trim());
    case "OL":
      return Array.from(b.children).map((li, idx) => `${idx + 1}. ` + (li.textContent || "").trim());
    case "PRE":
      return ["```", (b.textContent || "").trim(), "```"].filter(Boolean);
    default:
      return [text];
  }
}
async function renderFullCallout(plugin, type, title, bodyLines, sourcePath) {
  const md = [`> [!${type}] ${title}`];
  if (bodyLines.length) {
    md.push(">");
    for (const line of bodyLines) {
      for (const l of line.split("\n"))
        md.push("> " + l);
    }
  }
  const container = document.createElement("div");
  await import_obsidian5.MarkdownRenderer.render(plugin.app, md.join("\n"), container, sourcePath, new import_obsidian5.Component());
  return container.querySelector(".callout") || container;
}
async function processAdmonitions(plugin, el, sourcePath) {
  const children = Array.from(el.children);
  let i = 0;
  while (i < children.length) {
    const c = children[i];
    if (!(c instanceof HTMLElement) || c.tagName !== "P") {
      i++;
      continue;
    }
    const text = (c.textContent || "").trim();
    const open = /^:::\s*([a-zA-Z]+)(?:\[([^\]]*)\])?(?:\s+(.*))?$/.exec(text);
    if (open && text === open[0].trim()) {
      const bodyLines = [];
      let j = i + 1;
      let closed = false;
      for (; j < children.length; j++) {
        const n = children[j];
        if (n instanceof HTMLElement && n.tagName === "P" && /^:::\s*$/.test((n.textContent || "").trim())) {
          closed = true;
          break;
        }
        if (n instanceof HTMLElement)
          bodyLines.push(...blockToMarkdown(n));
      }
      const callout = await renderFullCallout(
        plugin,
        open[1].toLowerCase(),
        (open[2] || "").trim() || (open[3] || "").trim() || capitalise(open[1].toLowerCase()),
        bodyLines,
        sourcePath
      );
      if (closed && j < children.length)
        children[j].remove();
      c.replaceWith(callout);
      i = j + 1;
      continue;
    }
    const merged = splitMerged(text);
    if (merged) {
      const callout = await renderFullCallout(plugin, merged.type, merged.title, [merged.body], sourcePath);
      c.replaceWith(callout);
      i++;
      continue;
    }
    i++;
  }
}
function splitMerged(text) {
  const m = /^:::\s*([a-zA-Z]+)(?:\[([^\]]*)\])?(?:\s+(.*))?[\s\S]*?\s*:::\s*$/.exec(text);
  if (!m)
    return null;
  const type = m[1].toLowerCase();
  return { type, title: (m[2] || "").trim() || capitalise(type), body: (m[3] || "").trim() };
}

// src/livepreview.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
function capitalise2(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
var GithubCardWidget = class extends import_view.WidgetType {
  constructor(repo) {
    super();
    this.repo = repo;
  }
  eq(other) {
    return other.repo === this.repo;
  }
  estimateHeight() {
    return 120;
  }
  toDOM() {
    const card = buildGithubCard(this.repo);
    void hydrateGithubCard(card, this.repo);
    return card;
  }
  ignoreEvent() {
    return true;
  }
};
var SpoilerWidget = class extends import_view.WidgetType {
  constructor(text) {
    super();
    this.text = text;
  }
  eq(other) {
    return other.text === this.text;
  }
  toDOM() {
    const el = document.createElement("span");
    el.addClass("fuwari-lp-spoiler");
    el.setText(this.text);
    return el;
  }
  ignoreEvent() {
    return true;
  }
};
function cursorInside(view, from, to) {
  const sel = view.state.selection.main;
  return sel.from >= from && sel.to <= to;
}
function findCalloutBlocks(view) {
  const doc = view.state.doc;
  const blocks = [];
  const lineCount = doc.lines;
  let inFence = false;
  for (let ln = 1; ln <= lineCount; ln++) {
    const line = doc.line(ln);
    const text = line.text.trim();
    if (/^```/.test(text)) {
      inFence = !inFence;
      continue;
    }
    if (inFence)
      continue;
    const m = /^:::\s*([a-zA-Z]+)(?:\[([^\]]*)\])?(?:\s+(.*))?$/.exec(text);
    if (!m || text !== m[0].trim())
      continue;
    const type = m[1].toLowerCase();
    const title = (m[2] || "").trim() || (m[3] || "").trim() || capitalise2(type);
    const contentLines = [];
    let closeLine = -1;
    let innerFence = false;
    for (let ln2 = ln + 1; ln2 <= lineCount; ln2++) {
      const l2 = doc.line(ln2);
      const t2 = l2.text.trim();
      if (/^```/.test(t2)) {
        innerFence = !innerFence;
        contentLines.push(l2.text);
        continue;
      }
      if (innerFence) {
        contentLines.push(l2.text);
        continue;
      }
      if (/^:::\s*$/.test(t2)) {
        closeLine = ln2;
        break;
      }
      contentLines.push(l2.text);
    }
    if (closeLine === -1)
      continue;
    blocks.push({
      from: line.from,
      to: doc.line(closeLine).to,
      type,
      title,
      content: contentLines.join("\n")
    });
    ln = closeLine;
  }
  return blocks;
}
function computeCodeRanges(doc) {
  const ranges = [];
  const lineCount = doc.lines;
  let inFence = false;
  let fenceStart = 0;
  for (let ln = 1; ln <= lineCount; ln++) {
    const line = doc.line(ln);
    if (/^```/.test(line.text.trim())) {
      if (!inFence) {
        inFence = true;
        fenceStart = line.from;
      } else {
        ranges.push({ from: fenceStart, to: line.to });
        inFence = false;
      }
    }
  }
  const text = doc.toString();
  const re = /`+([^`]+)`+/g;
  let m;
  while (m = re.exec(text)) {
    const contentStart = m.index + m[0].indexOf(m[1]);
    ranges.push({ from: contentStart, to: contentStart + m[1].length });
  }
  return ranges;
}
function buildDecorations(view) {
  try {
    const items = [];
    const visible = view.visibleRanges;
    const codeRanges = computeCodeRanges(view.state.doc);
    const inCode = (pos) => codeRanges.some((r) => pos >= r.from && pos <= r.to);
    const blocks = findCalloutBlocks(view);
    const insideBlock = (pos) => blocks.some((b) => pos >= b.from && pos <= b.to);
    for (const { from, to } of visible) {
      const text = view.state.doc.sliceString(from, to);
      const githubRe = /::github\s*\{\s*repo\s*=\s*"([^"]+)"\s*\}/g;
      let m;
      while (m = githubRe.exec(text)) {
        const start = from + m.index;
        const end = start + m[0].length;
        if (cursorInside(view, start, end) || insideBlock(start) || inCode(start))
          continue;
        items.push({ from: start, to: end, deco: import_view.Decoration.replace({ widget: new GithubCardWidget(m[1]) }) });
      }
      const spoilerRe = /:spoiler\[([^\]]*)\]/g;
      while (m = spoilerRe.exec(text)) {
        const start = from + m.index;
        const end = start + m[0].length;
        if (cursorInside(view, start, end) || insideBlock(start) || inCode(start))
          continue;
        items.push({ from: start, to: end, deco: import_view.Decoration.replace({ widget: new SpoilerWidget(m[1]) }) });
      }
    }
    items.sort((a, b) => a.from - b.from || a.to - b.to);
    const builder = new import_state.RangeSetBuilder();
    for (const it of items)
      builder.add(it.from, it.to, it.deco);
    return builder.finish();
  } catch (e) {
    console.error("[fuwari-tools] live preview decoration error:", e);
    return import_view.Decoration.none;
  }
}
var LivePreviewDecoration = class {
  constructor(view) {
    this.decorations = buildDecorations(view);
  }
  update(update) {
    if (update.docChanged || update.selectionSet || update.viewportChanged) {
      this.decorations = buildDecorations(update.view);
    }
  }
};
var livePreviewExtension = import_view.ViewPlugin.fromClass(LivePreviewDecoration, {
  decorations: (v) => v.decorations
});

// src/main.ts
var NewPostModal = class extends import_obsidian6.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.contentEl.createEl("h3", { text: "\u65B0\u5EFA\u535A\u5BA2\u6587\u7AE0" });
    new import_obsidian6.Setting(this.contentEl).setName("\u6807\u9898").addText((t) => {
      this.titleInput = t.inputEl;
      t.setPlaceholder("\u6587\u7AE0\u6807\u9898");
      setTimeout(() => t.inputEl.focus(), 50);
    });
    new import_obsidian6.Setting(this.contentEl).setName("\u6807\u7B7E").setDesc("\u9017\u53F7\u5206\u9694").addText((t) => {
      this.tagsInput = t.inputEl;
      t.setPlaceholder("\u6280\u672F, \u7B14\u8BB0");
    });
    new import_obsidian6.Setting(this.contentEl).setName("\u5206\u7C7B").addText((t) => {
      this.catInput = t.inputEl;
      t.setPlaceholder("\u5B66\u4E60\u8BB0\u5F55");
    });
    const row = this.contentEl.createDiv({ cls: "fuwari-title-actions" });
    const create = row.createEl("button", { text: "\u521B\u5EFA", cls: "mod-cta" });
    create.addEventListener("click", () => this.submit());
    this.contentEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        this.submit();
      }
    });
  }
  submit() {
    const title = this.titleInput.value.trim() || "\u672A\u547D\u540D\u6587\u7AE0";
    const tags = this.tagsInput.value.split(/[,\n]/).map((s) => s.trim()).filter(Boolean);
    const category = this.catInput.value.trim();
    this.close();
    this.onSubmit(title, tags, category);
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FuwariToolsPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.processing = /* @__PURE__ */ new Set();
    this.warnThrottle = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    registerBlogRender(this);
    this.registerEditorExtension([livePreviewExtension]);
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian6.TFile)
          this.onFileModified(file);
      })
    );
    this.addCommand({
      id: "new-blog-post",
      name: "\u65B0\u5EFA\u535A\u5BA2\u6587\u7AE0",
      callback: () => this.newPost()
    });
    this.addCommand({
      id: "edit-blog-meta",
      name: "\u66F4\u6539\u6587\u4EF6\u5143\u6570\u636E",
      callback: () => this.editMeta()
    });
    this.addCommand({
      id: "publish-blog",
      name: "\u4E00\u952E\u53D1\u5E03\u535A\u5BA2",
      callback: () => this.publish()
    });
    this.addRibbonIcon("file-plus", "\u65B0\u5EFA\u535A\u5BA2\u6587\u7AE0", () => this.newPost());
    this.addRibbonIcon("pencil", "\u66F4\u6539\u6587\u4EF6\u5143\u6570\u636E", () => this.editMeta());
    this.addRibbonIcon("send", "\u4E00\u952E\u53D1\u5E03\u535A\u5BA2", () => this.publish());
    this.addSettingTab(new FuwariSettingTab(this.app, this));
  }
  onunload() {
    this.processing.clear();
    this.warnThrottle.clear();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  expandHome(p) {
    return p.replace(/^~(?=\/|$)/, (0, import_os.homedir)());
  }
  async newPost() {
    const postsFolder = this.settings.postsFolder.replace(/\/+$/, "");
    if (!this.app.vault.getAbstractFileByPath(postsFolder)) {
      await this.app.vault.createFolder(postsFolder);
    }
    new NewPostModal(this.app, async (title, tags, category) => {
      let slug = slugify(title);
      let path = `${postsFolder}/${slug}.md`;
      let i = 1;
      while (this.app.vault.getAbstractFileByPath(path)) {
        path = `${postsFolder}/${slug}-${i++}.md`;
      }
      const today = (0, import_obsidian6.moment)().format("YYYY-MM-DD");
      const q = (s) => `"${String(s).replace(/"/g, '\\"')}"`;
      const tagsYaml = tags.length ? tags.map(q).join(", ") : "";
      const content = [
        "---",
        `title: ${q(title)}`,
        `published: "${today}"`,
        `updated: "${today}"`,
        'description: ""',
        tags.length ? `tags: [${tagsYaml}]` : "tags: []",
        `category: ${q(category)}`,
        'image: ""',
        "draft: true",
        "---",
        ""
      ].join("\n");
      try {
        await this.app.vault.create(path, content);
        new import_obsidian6.Notice("\u5DF2\u521B\u5EFA\u6587\u7AE0\uFF08\u8349\u7A3F\uFF09\u3002\u5982\u9700\u8865\u6458\u8981/\u5C01\u9762\uFF0C\u7528\u300C\u7F16\u8F91\u5F53\u524D\u6587\u7AE0\u5143\u6570\u636E\u300D\u6216\u4FA7\u8FB9 AI \u6309\u94AE");
      } catch (e) {
        new import_obsidian6.Notice("\u521B\u5EFA\u5931\u8D25: " + e.message);
      }
    }).open();
  }
  editMeta() {
    const file = this.app.workspace.getActiveFile();
    if (!file) {
      new import_obsidian6.Notice("\u6CA1\u6709\u6253\u5F00\u7684\u6587\u7AE0");
      return;
    }
    if (file.extension !== "md" || !isUnder(file.path, this.settings.postsFolder)) {
      new import_obsidian6.Notice("\u8BF7\u6253\u5F00 posts \u76EE\u5F55\u4E0B\u7684\u6587\u7AE0");
      return;
    }
    new MetaModal(this.app, file, this).open();
  }
  async publish() {
    if (!this.settings.publishEnabled) {
      new import_obsidian6.Notice("\u53D1\u5E03\u529F\u80FD\u672A\u542F\u7528");
      return;
    }
    const script = this.expandHome(this.settings.publishScriptPath);
    new import_obsidian6.Notice("\u5F00\u59CB\u53D1\u5E03\u2026");
    (0, import_child_process.exec)(`/bin/bash "${script}"`, (error, stdout, stderr) => {
      const out = (stdout || "") + (stderr || "");
      if (error) {
        new import_obsidian6.Notice("\u53D1\u5E03\u5931\u8D25: " + error.message);
        return;
      }
      if (/VERIFY-HTTP\s+200/.test(out)) {
        new import_obsidian6.Notice("\u53D1\u5E03\u6210\u529F \u2705 \u5DF2\u4E0A\u7EBF");
      } else if (/SWAP-DONE/.test(out)) {
        new import_obsidian6.Notice("\u53D1\u5E03\u5B8C\u6210\uFF08\u68C0\u67E5\u7EBF\u4E0A\u72B6\u6001\uFF09");
      } else {
        new import_obsidian6.Notice("\u53D1\u5E03\u7ED3\u675F\uFF0C\u8BF7\u67E5\u770B\u7EBF\u4E0A");
      }
    });
  }
  onFileModified(file) {
    if (!isPostFile(file, this.settings.postsFolder))
      return;
    const fm = getFrontmatter(this.app, file);
    if (!fm)
      return;
    if (fm.title == null && fm.published == null)
      return;
    const today = (0, import_obsidian6.moment)().format("YYYY-MM-DD");
    const currentUpdated = fm.updated ? (0, import_obsidian6.moment)(fm.updated).format("YYYY-MM-DD") : "";
    if (this.settings.autoUpdateUpdated && currentUpdated !== today && !this.processing.has(file.path)) {
      const isDraft = fm.draft === true;
      if (!isDraft || this.settings.updateDrafts) {
        this.processing.add(file.path);
        this.app.fileManager.processFrontMatter(file, (nfm) => {
          nfm.updated = today;
        }).catch(() => {
        }).finally(() => this.processing.delete(file.path));
      }
    }
    if (this.settings.warnOnSave && fm.draft !== true) {
      const missing = [];
      if (!fm.published)
        missing.push("published");
      if (!fm.description)
        missing.push("description");
      if (missing.length) {
        const now = Date.now();
        const last = this.warnThrottle.get(file.path) || 0;
        if (now - last > 18e4) {
          this.warnThrottle.set(file.path, now);
          new import_obsidian6.Notice(`${file.basename}: \u7F3A\u5C11 ${missing.join("\u3001")}`, 5e3);
        }
      }
    }
  }
};
